---
title: "Stock Index Cointegration Analysis"
author: "Nova Nguyen"
date: "2023-10-17"
output: html_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(astsa) 
require(xts)
require(dplyr)
library(tseries) # Augmented Dickey-Fuller test
require(lmtest) # Durbin Watson test
require(fBasics) # normality tests of residuals
require(leaps)
require(urca) # ERS test of stationarity
library(lubridate)
library(tidyr)
library(strucchange) 
library(aTSA)
library(vars)
library(tsDyn)
```

## DATA PROCESSING

```{r Datasets}
#All cell information are read in as character variables

VNI <- read.csv("Datasets/VN Index Historical Data.csv")   # Vietnam
US <- read.csv("Datasets/SP500 Historical Prices.csv")   # US WSJ
CHN <- read.csv("Datasets/Shanghai Composite Historical Data.csv")   # China
HK <- read.csv("Datasets/Hang Seng Historical Data.csv")   # Hong Kong
JPN <- read.csv("Datasets/Nikkei 225 Historical Data.csv")   # Japan
SK <- read.csv("Datasets/KOSPI Historical Data.csv")   # South Korea
THL <- read.csv("Datasets/SET Index Historical Data.csv")   # Thailand
SGP <- read.csv("Datasets/STI Historical Prices.csv")   # Singapore WSJ
MSIA <- read.csv("Datasets/^KLSE.csv")   # Malaysia yahoo
PLP <- read.csv("Datasets/PSEi.PS.csv")   # Philippines yahoo
IND <- read.csv("Datasets/Jakarta Stock Exchange Composite Index Historical Data.csv")   # Indonesia
```

```{r Data Cleaning, warning = FALSE}

# Define a function for data processing
process <- function(data) {
  data = data %>%
    dplyr::select(Date, Price)
  data$Date = as.Date(data$Date, "%m/%d/%Y")
  data$Price = as.numeric(gsub(",", "", data$Price))
  data = data[order(data$Date),]
  return(data)
}

# Apply the data processing function to each dataframe
VNI = process(VNI)
CHN = process(CHN)
HK = process(HK)
JPN = process(JPN)
SK = process(SK)
THL = process(THL)
IND = process(IND)

## US
US = US %>%
  dplyr:::select(Date, Close)
US$Date = as.Date(US$Date, "%m/%d/%y")
US = US[order(US$Date),]
US <- rename(US, Price = Close)

## SGP
SGP = SGP %>%
  dplyr:::select(Date, Close)
SGP$Date = as.Date(SGP$Date, "%m/%d/%y")
SGP = SGP[order(SGP$Date),]
SGP <- rename(SGP, Price = Close)

## MSIA
MSIA = MSIA %>%
  dplyr:::select(Date, Close)
MSIA$Date = as.Date(MSIA$Date)
MSIA = MSIA[order(MSIA$Date),]
MSIA <- rename(MSIA, Price = Close)
MSIA = MSIA %>%
  mutate(Price = round(as.numeric(Price), 2)) %>%
  drop_na()

## PLP
PLP = PLP %>%
  dplyr:::select(Date, Close)
PLP$Date = as.Date(PLP$Date)
PLP = PLP[order(PLP$Date),]
PLP <- rename(PLP, Price = Close)
PLP = PLP %>%
  mutate(Price = round(as.numeric(Price), 2)) %>%
  drop_na()

```


```{r Merge into common df, warning = FALSE}

# List the dataframes  
dfs <- list(VNI, US, CHN, JPN, HK, SK, SGP, THL, MSIA, PLP, IND)

# Merge into one dataframe
df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

# Rename columns
colnames(df) <- c("Date", "VNI", "US", "CHN", "JPN", "HK", "SK", "SGP", "THL", "MSIA", "PLP", "IND")

head(df)
```


## TIME SERIES VISUALIZATION

```{r index price}
dfnames <- list("VNI", "US", "CHN", "JPN", "HK", "SK", "SGP", "THL", "MSIA", "PLP", "IND")
par(mfrow = c(2,2))

for(i in 1:length(dfnames)){
  tsplot(dfs[[i]]$Date, dfs[[i]]$Price, main = dfnames[i], ylab = '', xlab = '')
}
```

```{r log-return index price}
dfnames <- list("VNI", "US", "CHN", "JPN", "HK", "SK", "SGP", "THL", "MSIA", "PLP", "IND")
break_dates <- as.Date(c("2007-01-01", "2010-01-01", "2020-01-01", "2022-01-01"))

par(mfrow = c(2,2))

for(i in 1:length(dfnames)){
  tsplot(dfs[[i]]$Date, log(dfs[[i]]$Price), main = dfnames[i], ylim = c(5.0, 11.0), ylab = '', xlab = '')
  
  # Add vertical lines at specific dates
  for (date in break_dates) {
    abline(v = date, col = "red")
  }
}

```



```{r differential log return}
dfnames <- list("VNI", "US", "CHN", "JPN", "HK", "SK", "SGP", "THL", "MSIA", "PLP", "IND")
break_dates <- as.Date(c("2007-01-01", "2010-01-01", "2020-01-01", "2022-01-01"))

par(mfrow = c(2,2))

for(i in 1:length(dfnames)){
  tsplot(dfs[[i]]$Date[-1], diff(log(dfs[[i]]$Price)), main = dfnames[i], ylim = c(-0.1, 0.1), ylab = '', xlab = '')
  
  # Add vertical lines at specific dates
  for (date in break_dates) {
    abline(v = date, col = "red")
  }
}

```

## SUMMARY STATISTICS

```{r}
for(i in 1:length(dfs)){
  returns <- diff(log(as.data.frame(dfs[i])$Price))
  print(dfnames[i])
  print(summary(returns))
}
```

```{r pre GFC}
for (i in 1:length(dfs)) {
  # Filter the data frame to include only rows before 2007-01-01
  filtered_data <- dfs[[i]][dfs[[i]]$Date < as.Date("2007-01-01"), ]

  if (nrow(filtered_data) > 0) {
    # Calculate returns for the filtered data
    returns <- diff(log(filtered_data$Price))
    
    # Print the dataframe name (dfnames[i]) and summary statistics
    print(dfnames[i])
    print(summary(returns))
    tsplot(filtered_data$Date[-1], diff(log(filtered_data$Price)), main = dfnames[i], ylim = c(-0.05, 0.05), ylab = '', xlab = '')
    print(sd(returns))
  }
}
```

```{r post GFC}
for (i in 1:length(dfs)) {
  # Filter the data frame to include only rows after 2010 and before 2015
  filtered_data <- dfs[[i]][dfs[[i]]$Date >= as.Date("2010-01-01") & dfs[[i]]$Date < as.Date("2015-01-01"), ]

  if (nrow(filtered_data) > 0) {
    # Calculate returns for the filtered data
    returns <- diff(log(filtered_data$Price))
    
    # Print the dataframe name (dfnames[i]) and summary statistics
    print(dfnames[i])
    print(summary(returns))
    tsplot(filtered_data$Date[-1], diff(log(filtered_data$Price)), main = dfnames[i], ylim = c(-0.05, 0.05), ylab = '', xlab = '')
    print(sd(returns))
  }
}
```

```{r pre Covid}
for (i in 1:length(dfs)) {
  # Filter the data frame to include only rows after 2015 and before 2020
  filtered_data <- dfs[[i]][dfs[[i]]$Date >= as.Date("2015-01-01") & dfs[[i]]$Date < as.Date("2020-01-01"), ]

  if (nrow(filtered_data) > 0) {
    # Calculate returns for the filtered data
    returns <- diff(log(filtered_data$Price))
    
    # Print the dataframe name (dfnames[i]) and summary statistics
    print(dfnames[i])
    print(summary(returns))
    tsplot(filtered_data$Date[-1], diff(log(filtered_data$Price)), main = dfnames[i], ylim = c(-0.05, 0.05), ylab = '', xlab = '')
    print(sd(returns))
  }
}
```

```{r post Covid}
for (i in 1:length(dfs)) {
  # Filter the data frame to include only rows after 2023
  filtered_data <- dfs[[i]][dfs[[i]]$Date >= as.Date("2023-01-01"), ]

  if (nrow(filtered_data) > 0) {
    # Calculate returns for the filtered data
    returns <- diff(log(filtered_data$Price))
    
    # Print the dataframe name (dfnames[i]) and summary statistics
    print(dfnames[i])
    print(summary(returns))
    tsplot(filtered_data$Date[-1], diff(log(filtered_data$Price)), main = dfnames[i], ylim = c(-0.04, 0.04), ylab = '', xlab = '')
    print(sd(returns))
  }
}
```




## UNIT ROOT TEST

```{r stock index}

for(i in 1:length(dfs)){
  print(dfnames[i])
  print(tseries:::adf.test(log(as.data.frame(dfs[i])$Price)))
  print(tseries:::pp.test(log(as.data.frame(dfs[i])$Price)))
}
```

```{r stock return 1st difference}
for(i in 1:length(dfs)){
  print(dfnames[i])
  print(tseries:::adf.test(diff(log(as.data.frame(dfs[i])$Price))))
  print(tseries:::pp.test(diff(log(as.data.frame(dfs[i])$Price))))
}
```

## GRANGER CAUSALITY


```{r VN - each country pre GFC}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  df <- df %>%
    filter(Date < as.Date('2007-01-01')) %>%
    dplyr:::select(-Date)
  
  select <- VARselect(df, lag.max = 10)

  result1 <- grangertest(diff(log(df$VNI)), diff(log(df[,2])), order = as.numeric(select$selection[1]))
  result2 <- grangertest(diff(log(df[,2])), diff(log(df$VNI)), order = as.numeric(select$selection[1]))

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result1)
  print(result2)
}
```


```{r VN - each country during GFC}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  df <- df %>%
    filter(Date >= as.Date('2007-01-01') & Date < as.Date('2010-01-01')) %>%
    dplyr:::select(-Date)
  
  select <- VARselect(df, lag.max = 10)

  result1 <- grangertest(diff(log(df$VNI)), diff(log(df[,2])), order = as.numeric(select$selection[1]))
  result2 <- grangertest(diff(log(df[,2])), diff(log(df$VNI)), order = as.numeric(select$selection[1]))

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result1)
  print(result2)
}
```


```{r VN - each country post GFC}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  df <- df %>%
    filter(Date >= as.Date('2010-01-01') & Date < as.Date('2015-01-01')) %>%
    dplyr:::select(-Date)
  
  select <- VARselect(df, lag.max = 10)

  result1 <- grangertest(diff(log(df$VNI)), diff(log(df[,2])), order = as.numeric(select$selection[1]))
  result2 <- grangertest(diff(log(df[,2])), diff(log(df$VNI)), order = as.numeric(select$selection[1]))

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result1)
  print(result2)
}
```

```{r VN - each country pre Covid}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  df <- df %>%
    filter(Date >= as.Date('2015-01-01') & Date < as.Date('2020-01-01')) %>%
    dplyr:::select(-Date)
  
  select <- VARselect(df, lag.max = 10)

  result1 <- grangertest(diff(log(df$VNI)), diff(log(df[,2])), order = as.numeric(select$selection[1]))
  result2 <- grangertest(diff(log(df[,2])), diff(log(df$VNI)), order = as.numeric(select$selection[1]))

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result1)
  print(result2)
}
```

```{r VN - each country during Covid}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  df <- df %>%
    filter(Date >= as.Date('2020-01-01') & Date < as.Date('2023-01-01')) %>%
    dplyr:::select(-Date)
  
  select <- VARselect(df, lag.max = 10)

  result1 <- grangertest(diff(log(df$VNI)), diff(log(df[,2])), order = as.numeric(select$selection[1]))
  result2 <- grangertest(diff(log(df[,2])), diff(log(df$VNI)), order = as.numeric(select$selection[1]))

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result1)
  print(result2)
}
```

```{r VN - each country post Covid}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  df <- df %>%
    filter(Date >= as.Date('2023-01-01')) %>%
    dplyr:::select(-Date)
  
  select <- VARselect(df, lag.max = 10)

  result1 <- grangertest(diff(log(df$VNI)), diff(log(df[,2])), order = as.numeric(select$selection[1]))
  result2 <- grangertest(diff(log(df[,2])), diff(log(df$VNI)), order = as.numeric(select$selection[1]))

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result1)
  print(result2)
}
```

##EG TEST

```{r EG pre GFC}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  
  df <- df %>%
  filter(Date >= as.Date("2003-10-01"), Date < as.Date("2007-01-01"))

  result <- aTSA::coint.test(log(df$VNI), log(df[,3]), d = 0, output = TRUE)

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result)
}

```


```{r EG during GFC}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  
  df <- df %>%
  filter(Date >= as.Date("2007-01-01"), Date < as.Date("2010-01-01"))

  result <- aTSA::coint.test(log(df$VNI), log(df[,3]), d = 0, output = TRUE)

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result)
}
```


```{r EG post GFC}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  
  df <- df %>%
  filter(Date >= as.Date("2010-01-01"), Date < as.Date("2015-01-01"))

  result <- aTSA::coint.test(log(df$VNI), log(df[,3]), d = 0, output = TRUE)

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result)
}
```


```{r EG pre Covid}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  
  df <- df %>%
  filter(Date >= as.Date("2015-01-01"), Date < as.Date("2020-01-01"))

  result <- aTSA::coint.test(df$VNI, df[,3], d = 0, output = TRUE)

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result)
}
```


```{r EG during Covid}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  
  df <- df %>%
  filter(Date >= as.Date("2020-01-01"), Date < as.Date("2023-01-01"))

  result <- aTSA::coint.test(df$VNI, df[,3], d = 0, output = TRUE)

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result)
}
```


```{r EG post Covid}
for(i in 2:length(dfs)){

  # Merge VNI with each df
  df <- Reduce(function(x, y) merge(x, y, by = "Date"), list(VNI, dfs[i]))
 
  # Rename columns
  colnames(df) <- c("Date", "VNI", dfnames[i])
  
  df <- df %>%
  filter(Date >= as.Date("2023-01-01"))

  result <- aTSA::coint.test(df$VNI, df[,3], d = 0, output = TRUE)

  # Conduct ADF test on residuals
  print(dfnames[i])
  print(result)
}
```


##JOHANSEN COINTEGRATION TEST 

```{r EA1}
dfs <- list(VNI, CHN, JPN, HK, SK)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "CHN", "JPN", "HK", "SK")

df <- df %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #4
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 3, spec = "longrun")
summary(johansen)
```



```{r SEA1}
dfs <- list(VNI, SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #7
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 6, spec = "longrun")
summary(johansen)
```


```{r EA2 pre GFC}
dfs <- list(VNI, CHN, JPN, HK, SK)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "CHN", "JPN", "HK", "SK")

df <- df %>%
  filter(Date < as.Date("2007-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #1
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```


```{r SEA pre GFC}
dfs <- list(VNI, SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  filter(Date < as.Date("2007-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #4
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```



```{r EA during GFC}
dfs <- list(VNI, CHN, JPN, HK, SK)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "CHN", "JPN", "HK", "SK")

df <- df %>%
  filter(Date >= as.Date("2007-01-01"), Date < as.Date("2010-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #2
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```

```{r SEA during GFC}
dfs <- list(VNI, SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  filter(Date >= as.Date("2007-01-01"), Date < as.Date("2010-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #2
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```

```{r SEA3 sans VNI during GFC}
dfs <- list(SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  filter(Date >= as.Date("2007-01-01"), Date < as.Date("2010-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #2
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```



```{r EA post GFC}
dfs <- list(VNI, CHN, JPN, HK, SK)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "CHN", "JPN", "HK", "SK")

df <- df %>%
  filter(Date >= as.Date("2010-01-01"), Date < as.Date("2015-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #1
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```

```{r SEA post GFC}
dfs <- list(VNI, SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  filter(Date >= as.Date("2010-01-01"), Date < as.Date("2015-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #4
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 3, spec = "longrun")
summary(johansen)
```



```{r EA pre Covid}
dfs <- list(VNI, CHN, JPN, HK, SK)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "CHN", "JPN", "HK", "SK")

df <- df %>%
  filter(Date >= as.Date("2015-01-01"), Date < as.Date("2020-01-01")) %>%
  dplyr:::select(-Date)

select <-VARselect(df, lag.max = 7, type = "const") #3
select$selection

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```

```{r SEA pre Covid}
dfs <- list(VNI, SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  filter(Date >= as.Date("2015-01-01"), Date < as.Date("2020-01-01")) %>%
  dplyr:::select(-Date)

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```



```{r EA during Covid}
dfs <- list(VNI, CHN, JPN, HK, SK)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "CHN", "JPN", "HK", "SK")

df <- df %>%
  filter(Date >= as.Date("2020-01-01"), Date < as.Date("2023-01-01")) %>%
  dplyr:::select(-Date)

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```

```{r SEA during Covid}
dfs <- list(VNI, SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  filter(Date >= as.Date("2020-01-01"), Date < as.Date("2023-01-01")) %>%
  dplyr:::select(-Date)

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```



```{r EA post Covid}
dfs <- list(VNI, CHN, JPN, HK, SK)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "CHN", "JPN", "HK", "SK")

df <- df %>%
  filter(Date >= as.Date("2023-01-01")) %>%
  dplyr:::select(-Date)

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```

```{r SEA post Covid}
dfs <- list(VNI, SGP, THL, MSIA, PLP, IND)

df <- Reduce(function(x, y) merge(x, y, by = "Date"), dfs)

colnames(df) <- c("Date", "VNI", "SGP", "THL", "MSIA", "PLP", "IND")

df <- df %>%
  filter(Date >= as.Date("2023-01-01")) %>%
  dplyr:::select(-Date)

johansen <- ca.jo(df, type = "eigen", ecdet = "none", K = 2, spec = "longrun")
summary(johansen)
```




## STRUCTURAL BREAKS DETECTION

```{r}

dfs <- list(VNI, US, CHN, JPN, HK, SK, SGP, THL, MSIA, PLP, IND)

for(i in 1:length(dfs)){
  y = as.data.frame(dfs[i])$Price

  dat <- tibble(ylag0 = y,
                ylag1 = lag(y)
                ) %>%
    drop_na()

  qlr <- Fstats(ylag0 ~ ylag1, data = dat)

  bp <- breakpoints(qlr, h = 2, breaks = NULL)
  bp

  sctest(qlr, type = "supF")

  plot(qlr, main = paste(dfnames[i], as.data.frame(dfs[i])[as.numeric(bp[1]), 1]))
  lines(bp)
}
```





